sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ooeeqa/zsJz+xt9tG8lOcEfnJBEOBVCfBu435N6QQTzh+7OJY/AHzRNcudog4ihAGLbezcjYy7QPvBp4xpb7uPGZk/P4vDXeK/t4SM21vjxKi+GBVFCI8mOIoAfM+rY5nhWvBA/12mM+UnJYaQKAzzQ+luir6+tvHqF6qxCGKyd4xrFH+/nudOsTMIgoxHC3Bq8ZUtzzEvVvA/B6e1k2Ln+WkBlOe8f+G0wDd7nndESBbB6nQlN7RW4O6uUudCSlzGTvp7LfIlGnC1t7imPjDQwkEPuxeyIcg4J7ZBs5UqToAvqdRI35Vs6oOZNNmu6YVHEaK1XjHQikS9wLwYhHthu2eMJlxgvfLBdaG7d8+Lou+f+X4aoJyJf3sQruhfNYCn1pW705VZ21Ah8CA/HI3jLQ1IHmnGwkoIjqWRaqGkLV1cbc9XF8XLyaKQ/hYJl5dHT7O7sHOELua5LpMxzzA5vm3KW+yJmJwAs1PtTkaF2ejEtQ2tTqurDzOtSC3gHD4AgMSuVD5/5soSDNa8HdsoslAtocYVrY5cm9d95TV7Ogq/rKZWnXNiBpR/4cvfTohUSf78t42jROfhPeK1mzgxo7ryj5HKgOdAjQ1ibtr78bjAhkbs4sB22t+grhrncKGVUqPwgryEWrP79cEBnHa1KNbe1pLgPDAfh7o6gG3l4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/La-Divina-Commedia-di-Dante_1012
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy